import { Josefin_Sans } from 'next/font/google';
import './globals.css';

const font = Josefin_Sans({
	subsets: ['latin'],
	weight: ['300', '400', '600'],
});

export const metadata = {
	title: 'Base Apparel coming soon page',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${font.className} bg-gradient-to-tr from-white to-[#FFF4F4]`}
			>
				{children}
			</body>
		</html>
	);
}
